/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.clinicalmall.kuaixiu.controller;

import com.clinicalmall.kuaixiu.vo.CommonResponse;
import org.springframework.core.io.Resource;
import com.clinicalmall.kuaixiu.vo.SendSmsCodeRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Optional;

@Api(value = "Common", description = "the Common API")
public interface CommonApi {

	@ApiOperation(value = "获取附件", nickname = "getAttachment", notes = "", tags = { "common", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful operation") })
	@ApiImplicitParams({})
	@RequestMapping(value = "/common/attachment/{attachmentId}", produces = "application/octet-stream",
			// consumes = "application/json",
			method = RequestMethod.GET)
	ResponseEntity<Void> getAttachment(
			@ApiParam(value = "附件ID", required = true) @PathVariable("attachmentId") String attachmentId);

	@ApiOperation(value = "发送短信验证码", nickname = "sendSmsCode", notes = "", response = CommonResponse.class, tags = {
			"common", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "successful operation", response = CommonResponse.class) })
	@ApiImplicitParams({})
	@RequestMapping(value = "/common/sendSmsCode", produces = "application/json", consumes = "application/json", method = RequestMethod.POST)
	ResponseEntity<CommonResponse> sendSmsCode(
			@ApiParam(value = "发送短信验证码", required = true) @Valid @RequestBody SendSmsCodeRequest body);

	@ApiOperation(value = "上传附件", nickname = "uploadAttachment", notes = "", response = CommonResponse.class, tags = {
			"common", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "successful operation", response = CommonResponse.class) })
	@ApiImplicitParams({
			@ApiImplicitParam(name = "token", value = "token", required = true, dataType = "String", paramType = "header") })
	@RequestMapping(value = "/common/uploadAttachment", produces = "application/json", consumes = "multipart/form-data", method = RequestMethod.POST)
	ResponseEntity<CommonResponse> uploadAttachment(
			@ApiParam(value = "token", required = true) @RequestHeader(value = "token", required = true) String token,
			@ApiParam(value = "附件文件") @Valid @RequestPart("file") MultipartFile file,
			@ApiParam(value = "文件类型<br>0、未定义  1、图片 2、语音 3、文件") @RequestPart(value = "type", required = false) Integer type);

}
