swagger: '2.0'
info:
  description: |
    云快修接口定义
  version: 1.0.0
  title: 云快修
  termsOfService: http://swagger.io/terms/
  contact:
    email: jiff.zuo@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /jiff/eLabCloud/1.0.0
tags:
- name: common
  description: 公共接口
- name: org
  description: 组织接口
- name: user
  description: 用户接口
schemes:
- https
- http
paths:
  /org/register:
    post:
      tags:
      - org
      summary: 组织注册
      description: 组织注册
      operationId: register
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Order
        required: true
        schema:
          $ref: '#/definitions/OrgRegisterRequest'
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/CommonResponse'
definitions:
  OrgRegisterRequest:
    type: object
    properties:
      type:
        type: integer
      mobile:
        type: string
      name:
        type: string
      password:
        type: string
      code:
        type: string
    example:
      password: password
      code: code
      mobile: mobile
      name: name
      type: 0
    xml:
      name: OrgRegisterRequest
  CommonResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      msg:
        type: string
    example:
      msg: msg
      code: 0
parameters:
  tokenParam:
    name: token
    in: header
    description: token
    required: true
    type: string
  userIdParam:
    name: userId
    in: query
    description: userId
    required: true
    type: string